name: app-deployment
on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull the latest code
        run: |
          cd /workspace/node-app-deployment/actions-runner/node-app
          git pull origin main

      - name: Run App container
        run: |
          cd /workspace/node-app-deployment/actions-runner/node-app
          docker stop NodeApp && docker rm NodeApp
          docker image rmi -f node-app
          docker build -t node-app .
          docker run -d --name NodeApp -p 3010:3010 node-app
